Algoritmo "Glicose"

Var

  classificao : caractere
  glicose : real
  
Inicio

      escreva ("Digite a medida de glicose = ")
      leia (glicose)
      
      se glicose <= 100 entao
         escreva ("Classificação Normal")
         senao
              se glicose <= 140 entao
              escreva ("Classificacao: elevado")
              senao
              escreva ("Classificacao: diabetes")
              fimse
         fimse





Fimalgoritmo