Algoritmo "Contando Carneiros"




Var

 carneiro : inteiro
 x : caractere

Inicio

      carneiro <- (0)

      escreva ("Você dormiu ? ")
      leia (x)
      
      se (X = "n") entao
         enquanto (x <> "s") faca
         escreva ("Você dormiu ? ")
         leia (x)
         carneiro <- (carneiro + 1)
         fimenquanto
      senao
      escreva ("Contou 0 carneiros")
      fimse
      
      escreva ("Contou ", carneiro, " carneiros")





Fimalgoritmo